/* Auto-generated character offsets for CITIZEN_2 */
/* Generated by convertCharacter.py --calculate-offsets */

#pragma once

/* Part offsets (PS1 coords: X=right, Y=down, Z=forward) */
#define CITIZEN_2_BODY_OFFSET_X 0
#define CITIZEN_2_BODY_OFFSET_Y 0
#define CITIZEN_2_BODY_OFFSET_Z 0

#define CITIZEN_2_HEAD_OFFSET_X 2
#define CITIZEN_2_HEAD_OFFSET_Y -12
#define CITIZEN_2_HEAD_OFFSET_Z 6

#define CITIZEN_2_ARM_LEFT_OFFSET_X 24
#define CITIZEN_2_ARM_LEFT_OFFSET_Y -31
#define CITIZEN_2_ARM_LEFT_OFFSET_Z 0

#define CITIZEN_2_ARM_RIGHT_OFFSET_X -24
#define CITIZEN_2_ARM_RIGHT_OFFSET_Y -31
#define CITIZEN_2_ARM_RIGHT_OFFSET_Z 0

#define CITIZEN_2_LEG_LEFT_OFFSET_X 13
#define CITIZEN_2_LEG_LEFT_OFFSET_Y 64
#define CITIZEN_2_LEG_LEFT_OFFSET_Z 0

#define CITIZEN_2_LEG_RIGHT_OFFSET_X -13
#define CITIZEN_2_LEG_RIGHT_OFFSET_Y 64
#define CITIZEN_2_LEG_RIGHT_OFFSET_Z 0
