/* Auto-generated character offsets for CITIZEN_1 */
/* Generated by convertCharacter.py --calculate-offsets */

#pragma once

/* Part offsets (PS1 coords: X=right, Y=down, Z=forward) */
#define CITIZEN_1_BODY_OFFSET_X 0
#define CITIZEN_1_BODY_OFFSET_Y 0
#define CITIZEN_1_BODY_OFFSET_Z 0

#define CITIZEN_1_HEAD_OFFSET_X 0
#define CITIZEN_1_HEAD_OFFSET_Y -26
#define CITIZEN_1_HEAD_OFFSET_Z 9

#define CITIZEN_1_ARM_LEFT_OFFSET_X 24
#define CITIZEN_1_ARM_LEFT_OFFSET_Y -29
#define CITIZEN_1_ARM_LEFT_OFFSET_Z 0

#define CITIZEN_1_ARM_RIGHT_OFFSET_X -24
#define CITIZEN_1_ARM_RIGHT_OFFSET_Y -29
#define CITIZEN_1_ARM_RIGHT_OFFSET_Z 0

#define CITIZEN_1_LEG_LEFT_OFFSET_X 13
#define CITIZEN_1_LEG_LEFT_OFFSET_Y 53
#define CITIZEN_1_LEG_LEFT_OFFSET_Z 0

#define CITIZEN_1_LEG_RIGHT_OFFSET_X -13
#define CITIZEN_1_LEG_RIGHT_OFFSET_Y 53
#define CITIZEN_1_LEG_RIGHT_OFFSET_Z 0
