/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by tools/parseNeighborhood.py from neighborhood.png
 */

#pragma once

#include <stdint.h>

/*============================================================================
 * MAP CONFIGURATION
 *============================================================================*/

#define MAP_PIXELS          64
#define MAP_SCALE           512
#define MAP_WORLD_SIZE      32768
#define MAP_ORIGIN_X        (-MAP_WORLD_SIZE / 2)
#define MAP_ORIGIN_Z        (-MAP_WORLD_SIZE / 2)

/*============================================================================
 * PLAYER SPAWN
 *============================================================================*/

#define PLAYER_SPAWN_X      -12800
#define PLAYER_SPAWN_Z      0

/*============================================================================
 * HOUSES
 *============================================================================*/

#define NUM_MAP_HOUSES      7

typedef struct {
    int32_t x, z;           /* World position */
    int16_t rotation;       /* Y rotation (0, 1024, 2048, 3072) */
    uint16_t address;       /* House address from map coords (XXYY format) */
    uint8_t modelType;      /* 0=hut1, 1=hut2, 2=hut3 */
} HouseSpawn;

extern const HouseSpawn mapHouses[NUM_MAP_HOUSES];

/*============================================================================
 * TREES
 *============================================================================*/

#define NUM_MAP_TREES       19

typedef struct {
    int32_t x, z;           /* World position */
    uint8_t variant;        /* 0=large tree, 1=small tree */
} TreeSpawn;

extern const TreeSpawn mapTrees[NUM_MAP_TREES];

/*============================================================================
 * FENCE POSTS (tile-based)
 *============================================================================*/

#define NUM_FENCE_POSTS     155

typedef struct {
    int32_t x, z;           /* World position (tile center) */
} FencePost;

extern const FencePost mapFencePosts[NUM_FENCE_POSTS];

/*============================================================================
 * STREET TILES
 *============================================================================*/

/* Bitmap for fast street tile lookup (64x64 grid = 512 bytes) */
extern const uint8_t streetTileBitmap[512];

/* Check if a map pixel is a street tile */
#define IS_STREET_PIXEL(px, pz) \
    ((px) >= 0 && (px) < 64 && (pz) >= 0 && (pz) < 64 && \
     (streetTileBitmap[((pz) * 64 + (px)) / 8] & (1 << (((pz) * 64 + (px)) % 8))))
