#!/usr/bin/env python3
"""
Parse neighborhood.png map and generate world_data.h/c for PS1 game.

Map colors (exact RGB values):
- (29, 43, 83): Dark blue - out of bounds
- (116, 47, 41): Brown - fence perimeter
- (95, 87, 79): Grey - street tiles
- (18, 83, 89): Teal/dark green - trees
- (195, 0, 76): Red/magenta - houses
- (0, 178, 81): Bright green - player spawn (restaurant)
"""

import argparse
from PIL import Image
from pathlib import Path
import math

# Exact colors from the map
COLOR_BACKGROUND = (29, 43, 83)    # Dark blue - out of bounds
COLOR_FENCE = (116, 47, 41)        # Brown - fence
COLOR_STREET = (95, 87, 79)        # Grey - street
COLOR_TREE = (18, 83, 89)          # Teal - trees
COLOR_HOUSE = (195, 0, 76)         # Red/magenta - houses
COLOR_SPAWN = (0, 178, 81)         # Bright green - player spawn

# Map configuration
MAP_PIXELS = 64
FLOOR_TILE_SIZE = 512  # Must match FLOOR_TILE_SIZE in game_config.h
TILES_PER_PIXEL = 1    # Each map pixel represents this many floor tiles
MAP_SCALE = FLOOR_TILE_SIZE * TILES_PER_PIXEL  # 1 pixel = 512 world units
MAP_WORLD_SIZE = MAP_PIXELS * MAP_SCALE  # 32768


def pixel_to_world(px, pz):
    """Convert pixel coordinates to world coordinates (centered at origin)."""
    wx = (px - MAP_PIXELS // 2) * MAP_SCALE
    wz = (pz - MAP_PIXELS // 2) * MAP_SCALE
    return wx, wz


def find_connected_regions(img, target_color):
    """Find connected regions of a specific color using flood fill."""
    width, height = img.size
    visited = set()
    regions = []

    def flood_fill(start_x, start_y):
        """Return all pixels in connected region."""
        region = []
        stack = [(start_x, start_y)]
        while stack:
            x, y = stack.pop()
            if (x, y) in visited:
                continue
            if x < 0 or x >= width or y < 0 or y >= height:
                continue
            if img.getpixel((x, y)) != target_color:
                continue
            visited.add((x, y))
            region.append((x, y))
            # 4-connected neighbors
            stack.extend([(x+1, y), (x-1, y), (x, y+1), (x, y-1)])
        return region

    for y in range(height):
        for x in range(width):
            if (x, y) not in visited and img.getpixel((x, y)) == target_color:
                region = flood_fill(x, y)
                if region:
                    regions.append(region)

    return regions


def region_center(region):
    """Calculate center of a region."""
    if not region:
        return 0, 0
    sum_x = sum(p[0] for p in region)
    sum_y = sum(p[1] for p in region)
    return sum_x // len(region), sum_y // len(region)


def find_nearest_street_direction(img, px, pz):
    """Find the direction to nearest street tile for house orientation."""
    width, height = img.size
    best_dist = float('inf')
    best_dir = 0  # Default facing

    # Search in cardinal directions
    directions = [
        (0, -1, 0),      # North (facing -Z) -> rotation 0
        (1, 0, 1024),    # East (facing +X) -> rotation 1024 (90 deg)
        (0, 1, 2048),    # South (facing +Z) -> rotation 2048 (180 deg)
        (-1, 0, 3072),   # West (facing -X) -> rotation 3072 (270 deg)
    ]

    for dx, dy, rotation in directions:
        # Search along this direction
        for dist in range(1, 20):
            nx = px + dx * dist
            ny = pz + dy * dist
            if 0 <= nx < width and 0 <= ny < height:
                if img.getpixel((nx, ny)) == COLOR_STREET:
                    if dist < best_dist:
                        best_dist = dist
                        best_dir = rotation
                    break

    return best_dir


def collect_fence_posts(img):
    """Collect all fence pixel positions as individual posts (tile-based)."""
    width, height = img.size
    posts = []

    for y in range(height):
        for x in range(width):
            if img.getpixel((x, y)) == COLOR_FENCE:
                wx, wz = pixel_to_world(x, y)
                posts.append((wx, wz))

    return posts


def generate_header(houses, trees, fence_posts, street_bitmap, spawn_x, spawn_z):
    """Generate world_data.h content."""
    lines = [
        "/*",
        " * AUTO-GENERATED FILE - DO NOT EDIT",
        " * Generated by tools/parseNeighborhood.py from neighborhood.png",
        " */",
        "",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "/*============================================================================",
        " * MAP CONFIGURATION",
        " *============================================================================*/",
        "",
        f"#define MAP_PIXELS          {MAP_PIXELS}",
        f"#define MAP_SCALE           {MAP_SCALE}",
        f"#define MAP_WORLD_SIZE      {MAP_WORLD_SIZE}",
        f"#define MAP_ORIGIN_X        (-MAP_WORLD_SIZE / 2)",
        f"#define MAP_ORIGIN_Z        (-MAP_WORLD_SIZE / 2)",
        "",
        "/*============================================================================",
        " * PLAYER SPAWN",
        " *============================================================================*/",
        "",
        f"#define PLAYER_SPAWN_X      {spawn_x}",
        f"#define PLAYER_SPAWN_Z      {spawn_z}",
        "",
        "/*============================================================================",
        " * HOUSES",
        " *============================================================================*/",
        "",
        f"#define NUM_MAP_HOUSES      {len(houses)}",
        "",
        "typedef struct {",
        "    int32_t x, z;           /* World position */",
        "    int16_t rotation;       /* Y rotation (0, 1024, 2048, 3072) */",
        "    uint16_t address;       /* House address from map coords (XXYY format) */",
        "    uint8_t modelType;      /* 0=hut1, 1=hut2, 2=hut3 */",
        "} HouseSpawn;",
        "",
        "extern const HouseSpawn mapHouses[NUM_MAP_HOUSES];",
        "",
        "/*============================================================================",
        " * TREES",
        " *============================================================================*/",
        "",
        f"#define NUM_MAP_TREES       {len(trees)}",
        "",
        "typedef struct {",
        "    int32_t x, z;           /* World position */",
        "    uint8_t variant;        /* 0=large tree, 1=small tree */",
        "} TreeSpawn;",
        "",
        "extern const TreeSpawn mapTrees[NUM_MAP_TREES];",
        "",
        "/*============================================================================",
        " * FENCE POSTS (tile-based)",
        " *============================================================================*/",
        "",
        f"#define NUM_FENCE_POSTS     {len(fence_posts)}",
        "",
        "typedef struct {",
        "    int32_t x, z;           /* World position (tile center) */",
        "} FencePost;",
        "",
        "extern const FencePost mapFencePosts[NUM_FENCE_POSTS];",
        "",
        "/*============================================================================",
        " * STREET TILES",
        " *============================================================================*/",
        "",
        "/* Bitmap for fast street tile lookup (64x64 grid = 512 bytes) */",
        "extern const uint8_t streetTileBitmap[512];",
        "",
        "/* Check if a map pixel is a street tile */",
        f"#define IS_STREET_PIXEL(px, pz) \\",
        f"    ((px) >= 0 && (px) < {MAP_PIXELS} && (pz) >= 0 && (pz) < {MAP_PIXELS} && \\",
        f"     (streetTileBitmap[((pz) * {MAP_PIXELS} + (px)) / 8] & (1 << (((pz) * {MAP_PIXELS} + (px)) % 8))))",
        "",
    ]
    return "\n".join(lines)


def generate_source(houses, trees, fence_posts, street_bitmap):
    """Generate world_data.c content."""
    lines = [
        "/*",
        " * AUTO-GENERATED FILE - DO NOT EDIT",
        " * Generated by tools/parseNeighborhood.py from neighborhood.png",
        " */",
        "",
        '#include "world_data.h"',
        "",
        "/*============================================================================",
        " * HOUSE DATA",
        " *============================================================================*/",
        "",
        "const HouseSpawn mapHouses[NUM_MAP_HOUSES] = {",
    ]

    for i, (x, z, rotation, address, model_type) in enumerate(houses):
        lines.append(f"    {{ .x = {x}, .z = {z}, .rotation = {rotation}, .address = {address}, .modelType = {model_type} }},")

    lines.extend([
        "};",
        "",
        "/*============================================================================",
        " * TREE DATA",
        " *============================================================================*/",
        "",
        "const TreeSpawn mapTrees[NUM_MAP_TREES] = {",
    ])

    for i, (x, z, variant) in enumerate(trees):
        lines.append(f"    {{ .x = {x}, .z = {z}, .variant = {variant} }},")

    lines.extend([
        "};",
        "",
        "/*============================================================================",
        " * FENCE POST DATA (tile-based)",
        " *============================================================================*/",
        "",
        "const FencePost mapFencePosts[NUM_FENCE_POSTS] = {",
    ])

    for x, z in fence_posts:
        lines.append(f"    {{ .x = {x}, .z = {z} }},")

    lines.extend([
        "};",
        "",
        "/*============================================================================",
        " * STREET TILE BITMAP",
        " *============================================================================*/",
        "",
        "const uint8_t streetTileBitmap[512] = {",
    ])

    # Format bitmap as rows of 16 bytes
    for row in range(0, 512, 16):
        byte_strs = [f"0x{street_bitmap[row + i]:02x}" for i in range(min(16, 512 - row))]
        lines.append("    " + ", ".join(byte_strs) + ",")

    lines.extend([
        "};",
        "",
    ])

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description='Parse neighborhood map and generate world data')
    parser.add_argument('input', help='Input PNG file (neighborhood.png)')
    parser.add_argument('output_header', help='Output header file (world_data.h)')
    parser.add_argument('output_source', help='Output source file (world_data.c)')
    args = parser.parse_args()

    print(f"Loading {args.input}...")
    img = Image.open(args.input).convert('RGB')

    if img.size != (MAP_PIXELS, MAP_PIXELS):
        print(f"Warning: Expected {MAP_PIXELS}x{MAP_PIXELS}, got {img.size}")

    # Find player spawn (bright green)
    spawn_px, spawn_pz = MAP_PIXELS // 2, MAP_PIXELS // 2  # Default center
    for y in range(img.height):
        for x in range(img.width):
            if img.getpixel((x, y)) == COLOR_SPAWN:
                spawn_px, spawn_pz = x, y
                print(f"  Player spawn at pixel ({x}, {y})")
                break
    spawn_x, spawn_z = pixel_to_world(spawn_px, spawn_pz)
    print(f"  Player spawn world position: ({spawn_x}, {spawn_z})")

    # Find houses (red regions)
    print("Finding houses...")
    house_regions = find_connected_regions(img, COLOR_HOUSE)
    houses = []
    for i, region in enumerate(house_regions):
        cx, cz = region_center(region)
        wx, wz = pixel_to_world(cx, cz)
        rotation = find_nearest_street_direction(img, cx, cz)
        model_type = i % 3  # Cycle through house models
        # Generate house address from pixel coordinates (XXYY format)
        address = cx * 100 + cz
        houses.append((wx, wz, rotation, address, model_type))
        print(f"  House {i}: pixel ({cx}, {cz}) -> world ({wx}, {wz}), rotation {rotation}, address {address}, model {model_type}")

    # Find trees (dark green pixels)
    print("Finding trees...")
    trees = []
    for y in range(img.height):
        for x in range(img.width):
            if img.getpixel((x, y)) == COLOR_TREE:
                wx, wz = pixel_to_world(x, y)
                variant = len(trees) % 2  # Alternate between large and small
                trees.append((wx, wz, variant))
    print(f"  Found {len(trees)} tree positions")

    # Collect fence posts (tile-based)
    print("Collecting fence posts...")
    fence_posts = collect_fence_posts(img)
    print(f"  Found {len(fence_posts)} fence posts")

    # Build street tile bitmap
    print("Building street tile bitmap...")
    street_bitmap = bytearray(512)  # 64*64/8 = 512 bytes
    street_count = 0
    for y in range(img.height):
        for x in range(img.width):
            if img.getpixel((x, y)) == COLOR_STREET:
                bit_index = y * MAP_PIXELS + x
                byte_index = bit_index // 8
                bit_offset = bit_index % 8
                street_bitmap[byte_index] |= (1 << bit_offset)
                street_count += 1
    print(f"  Found {street_count} street pixels")

    # Generate output files
    print(f"Writing {args.output_header}...")
    header_content = generate_header(houses, trees, fence_posts, street_bitmap, spawn_x, spawn_z)
    Path(args.output_header).parent.mkdir(parents=True, exist_ok=True)
    with open(args.output_header, 'w') as f:
        f.write(header_content)

    print(f"Writing {args.output_source}...")
    source_content = generate_source(houses, trees, fence_posts, street_bitmap)
    Path(args.output_source).parent.mkdir(parents=True, exist_ok=True)
    with open(args.output_source, 'w') as f:
        f.write(source_content)

    print("Done!")
    print(f"  Houses: {len(houses)}")
    print(f"  Trees: {len(trees)}")
    print(f"  Fence posts: {len(fence_posts)}")
    print(f"  Street pixels: {street_count}")


if __name__ == '__main__':
    main()
